services:
  frontend:
    build:
      context: ./web-rtc-client
    ports:
      - "8080:80"
    environment:
      - VITE_SIGNALING_SERVER_URL=${VITE_SIGNALING_SERVER_URL}
  signaling:
    build:
      context: ./signaling-server
    ports:
      - "3000:3000"